name: Build and Deploy WebAssembly

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Emscripten SDK
        uses: mymindstorm/setup-emsdk@v14

      - name: Verify Emscripten
        run: emcc -v

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Configure CMake for WebAssembly
        run: |
          mkdir -p build
          cd build
          emcmake cmake .. -DPLATFORM=Web

      - name: Build WebAssembly
        run: |
          cd build
          emmake make -j

      - name: Copy files to deployment directory
        run: |
          mkdir -p deploy
          cp build/index.html build/boids.js build/boids.wasm deploy/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
